apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
    app.kubernetes.io/part-of: togglemaster
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
