apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: togglemaster
spec:
  project: default
  source:
    repoURL: ${repo_url}
    targetRevision: ${revision}
    path: gitops/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
